version: "3"

services:
  specify7:
    build: ./specify7
    ports:
      - "65001:80"
    volumes:
      - ./specify7/specify6_thick_client:/usr/local/specify6
      - ./specify7/specify7_config:/usr/local/specify_config
      - ~/.specify7-docker/data/specify7/specify_wb_upload:/usr/local/specify_wb_upload
      - ~/.specify7-docker/data/specify7/specify_depository:/var/www/html/specify/specify_depository
